# Generated by Django 4.1.7 on 2023-02-24 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'finance_bill',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'finance_currency',
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'finance_expense_category',
            },
        ),
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'finance_income_category',
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('bill_source_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movements_source', to='finance.bill')),
                ('bill_target_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movements_target', to='finance.bill')),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='finance.currency')),
            ],
            options={
                'db_table': 'finance_movement',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='finance.incomecategory')),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='finance.currency')),
            ],
            options={
                'db_table': 'finance_income',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='finance.expensecategory')),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='finance.currency')),
            ],
            options={
                'db_table': 'finance_expense',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_currency', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exchanges_source', to='finance.currency')),
                ('target_currency', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exchanges_target', to='finance.currency')),
            ],
            options={
                'db_table': 'finance_exchange',
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='currency_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='finance.currency'),
        ),
    ]
